### ISSUE TITLE
Python unittest job name unify to filename, different name is unnecessary

### ISSUE THREAD

**Issue by aKuad** [aKuad/py-web-intercom#27]
## Description

On `python-unittest.yml` :

```yml
jobs:
  python-unittest:
    runs-on: ubuntu-latest
```

I think different name is unnecessary.
